on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version:
          - 7.1.3
          - 7.2.5
          - 8.0.2
          - 8.1.2
          - 8.2.0

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential ca-certificates libsqlite3-dev libxml2-dev pkg-config wget
          wget https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz
          tar -xzf php-${PHP_VERSION}.tar.gz
          cd php-${PHP_VERSION}
          ./configure --enable-sigchild --enable-pcntl --prefix /opt/php
          make
          make install
          mkdir ../build
          cd ../build
          mv /opt/php .
          tar -cvjf php-${PHP_VERSION}-pcntl-sigchild.tar.bz2 php
          rm -rf php
